version: '3'

services:
  fastapi:
    build: .
    image: capizani/fastapi-docker-CI
    container_name: fastapi-docker-container
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/app/