version: '3'

services:
  fastapi:
    image: capizani/fastapi-docker-ci
    container_name: fastapi-docker-container
    working_dir: /app
    command: bash -c " 
      coverage run -m pytest && coverage xml && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload "
    ports:
      - 8000:8000
    volumes:
      - .:/app/