name: ci-fastapi-workflow
on: 
  pull_request:
    branches:
      - develop
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!develop'   # excludes develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version
      - run: poetry install
      - run: pytest